/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Robots = {
  noIndex?: boolean;
  noFollow?: boolean;
};

export type SocialLinks = {
  facebook?: string;
  instagram?: string;
  linkedin?: string;
};

export type Link = {
  _type: "link";
  socialLinks?: SocialLinks;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Logo = {
  _type: "logo";
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Workshop = {
  _id: string;
  _type: "workshop";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: Img;
  description?: string;
  datetime?: string;
  location?: string;
  duration?: number;
  group?: "adult" | "teen" | "children" | "family";
  href?: string;
  status?: "inProgress" | "planned" | "completed";
  signupFormUrl?: string;
  materials?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type Img = {
  _type: "img";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type CardWithRedirect = {
  _id: string;
  _type: "cardWithRedirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: Img;
  description?: string;
  href?: string;
  hrefText?: string;
};

export type CardLandingPage = {
  _id: string;
  _type: "cardLandingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  image?: Img;
  description?: string;
};

export type RedirectButtonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "redirectButton";
};

export type CooperationSection = {
  _type: "cooperationSection";
  title?: string;
  description?: string;
  button?: RedirectButtonReference;
};

export type SupportSection = {
  _type: "supportSection";
  title?: string;
  description?: string;
  krsNumber?: string;
  backgroundImage?: Img;
  button?: RedirectButtonReference;
};

export type CardWithRedirectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "cardWithRedirect";
};

export type Cardswithredirect = {
  _type: "cardswithredirect";
  title?: string;
  subtitle?: string;
  cards?: Array<
    {
      _key: string;
    } & CardWithRedirectReference
  >;
  button?: RedirectButtonReference;
};

export type RedirectButton = {
  _id: string;
  _type: "redirectButton";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text?: string;
  href?: string;
};

export type CardLandingPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "cardLandingPage";
};

export type Cardswithbackground = {
  _type: "cardswithbackground";
  title?: string;
  subtitle?: string;
  backgroundImage?: Img;
  cards?: Array<
    {
      _key: string;
    } & CardLandingPageReference
  >;
};

export type HeroSection = {
  _type: "heroSection";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  subtitle?: string;
};

export type PostsSection = {
  _type: "postsSection";
  displayNumber?: number;
};

export type LeadSection = {
  _type: "leadSection";
  title?: string;
  subtitle?: string;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  canonical?: string;
  ogImage?: Img;
  twitterCreator?: string;
  robots?: Robots;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & Img)
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & LeadSection)
    | ({
        _key: string;
      } & PostsSection)
    | ({
        _key: string;
      } & Cardswithbackground)
    | ({
        _key: string;
      } & Cardswithredirect)
    | ({
        _key: string;
      } & SupportSection)
    | ({
        _key: string;
      } & CooperationSection)
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  logo?: Logo;
  link?: Link;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  icon?: IconPicker;
};

export type IconPicker = {
  _type: "iconPicker";
  provider?: string;
  name?: string;
  svg?: string;
};

export type Material = {
  _id: string;
  _type: "material";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  date?: string;
  event?: "Warsztaty" | "Konferencja" | "Webinar" | "Szkolenie" | "Inne";
  type?:
    | "Workbook"
    | "Checklist"
    | "Poradnik"
    | "Publikacja"
    | "Nagranie wideo"
    | "Szablon"
    | "Infografika"
    | "Inne";
  area?:
    | "Zdrowie"
    | "Prawo"
    | "Finanse"
    | "Kariera"
    | "Rozw\xF3j Osobisty"
    | "Rodzicielstwo"
    | "Inne";
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  format?: "PDF" | "Zip" | "MP4" | "Link" | "Inne";
  size?: string;
  placements?: Array<string>;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  image?: Img;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: RichText;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  img?: Img;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Robots
  | SocialLinks
  | Link
  | SanityImageAssetReference
  | Logo
  | SanityFileAssetReference
  | Workshop
  | Img
  | Slug
  | CardWithRedirect
  | CardLandingPage
  | RedirectButtonReference
  | CooperationSection
  | SupportSection
  | CardWithRedirectReference
  | Cardswithredirect
  | RedirectButton
  | CardLandingPageReference
  | Cardswithbackground
  | HeroSection
  | PostsSection
  | LeadSection
  | RichText
  | Seo
  | Home
  | SanityImageCrop
  | SanityImageHotspot
  | Settings
  | Category
  | IconPicker
  | Material
  | AuthorReference
  | CategoryReference
  | Post
  | Author
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/app/(root)/workshops/page.tsx
// Variable: workshopsQuery
// Query: *[_type == "workshop"] | order(_createdAt desc)
export type WorkshopsQueryResult = Array<{
  _id: string;
  _type: "workshop";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: Img;
  description?: string;
  datetime?: string;
  location?: string;
  duration?: number;
  group?: "adult" | "children" | "family" | "teen";
  href?: string;
  status?: "completed" | "inProgress" | "planned";
  signupFormUrl?: string;
  materials?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
}>;

// Source: ../web/app/page.tsx
// Variable: homeQuery
// Query: *[_type == "home"][0]{    _id,    sections[]{      ...,      _type in ["cardswithbackground", "sectionCardsWithBackground"] => {        ...,        cards[]->{          _id,          title,          description,          image        }      },      _type in ["cardswithredirect", "sectionCardsWithRedirect"] => {        ...,        cards[]->{          _id,          title,          description,          href,          hrefText,          image        },        button->{          _id,          text,          href        }      },      _type in ["supportSection", "sectionSupport"] => {        ...,        button->{          _id,          text,          href        }      },      _type in ["cooperationSection", "sectionCooperation"] => {        ...,        button->{          _id,          text,          href        }      }    }  }
export type HomeQueryResult = {
  _id: string;
  sections: Array<
    | {
        _key: string;
        _type: "cardswithbackground";
        title?: string;
        subtitle?: string;
        backgroundImage?: Img;
        cards?: Array<
          {
            _key: string;
          } & CardLandingPageReference
        >;
      }
    | {
        _key: string;
        _type: "cardswithbackground";
        title?: string;
        subtitle?: string;
        backgroundImage?: Img;
        cards: Array<{
          _id: string;
          title: string | null;
          description: string | null;
          image: Img | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "cardswithredirect";
        title?: string;
        subtitle?: string;
        cards?: Array<
          {
            _key: string;
          } & CardWithRedirectReference
        >;
        button?: RedirectButtonReference;
      }
    | {
        _key: string;
        _type: "cardswithredirect";
        title?: string;
        subtitle?: string;
        cards: Array<{
          _id: string;
          title: string | null;
          description: string | null;
          href: string | null;
          hrefText: string | null;
          image: Img | null;
        }> | null;
        button: {
          _id: string;
          text: string | null;
          href: string | null;
        } | null;
      }
    | {
        _key: string;
        _type: "cooperationSection";
        title?: string;
        description?: string;
        button?: RedirectButtonReference;
      }
    | {
        _key: string;
        _type: "cooperationSection";
        title?: string;
        description?: string;
        button: {
          _id: string;
          text: string | null;
          href: string | null;
        } | null;
      }
    | {
        _key: string;
        _type: "heroSection";
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        title?: string;
        subtitle?: string;
      }
    | {
        _key: string;
        _type: "img";
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
      }
    | {
        _key: string;
        _type: "leadSection";
        title?: string;
        subtitle?: string;
      }
    | {
        _key: string;
        _type: "postsSection";
        displayNumber?: number;
      }
    | {
        _key: string;
        _type: "supportSection";
        title?: string;
        description?: string;
        krsNumber?: string;
        backgroundImage?: Img;
        button?: RedirectButtonReference;
      }
    | {
        _key: string;
        _type: "supportSection";
        title?: string;
        description?: string;
        krsNumber?: string;
        backgroundImage?: Img;
        button: {
          _id: string;
          text: string | null;
          href: string | null;
        } | null;
      }
  > | null;
} | null;

// Source: ../web/sanity/queries/groq.example.ts
// Variable: postsQuery
// Query: *[_type == "post"] | order(_createdAt desc) {    _id,    _createdAt,    title,    "slug": slug.current,    "author": author->name,    "image": mainImage.asset->url,    description,    "categories": categories[]->title,    body  }
export type PostsQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  author: string | null;
  image: null;
  description: null;
  categories: Array<string | null> | null;
  body: RichText | null;
}>;

// Source: ../web/sanity/queries/materials.ts
// Variable: materialsQuery
// Query: *[_type == "material"] | order(date desc) {    _id,    title,    description,    date,    event,    type,    area,    format,    size,    placements,    "fileAsset": file.asset->{      url,      extension,      size    }  }
export type MaterialsQueryResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  date: string | null;
  event: "Inne" | "Konferencja" | "Szkolenie" | "Warsztaty" | "Webinar" | null;
  type:
    | "Checklist"
    | "Infografika"
    | "Inne"
    | "Nagranie wideo"
    | "Poradnik"
    | "Publikacja"
    | "Szablon"
    | "Workbook"
    | null;
  area:
    | "Finanse"
    | "Inne"
    | "Kariera"
    | "Prawo"
    | "Rodzicielstwo"
    | "Rozw\xF3j Osobisty"
    | "Zdrowie"
    | null;
  format: "Inne" | "Link" | "MP4" | "PDF" | "Zip" | null;
  size: string | null;
  placements: Array<string> | null;
  fileAsset: {
    url: string | null;
    extension: string | null;
    size: number | null;
  } | null;
}>;

// Source: ../web/sanity/queries/settings.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0] {    logo {      logo {        asset-> {          url        }      }    },    link {      socialLinks {        facebook,        instagram,        linkedin      }    }  }
export type SettingsQueryResult = {
  logo: {
    logo: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  } | null;
  link: {
    socialLinks: {
      facebook: string | null;
      instagram: string | null;
      linkedin: string | null;
    } | null;
  } | null;
} | null;

// Source: ../web/sanity/queries/settings.ts
// Variable: logoQuery
// Query: *[_type == "settings"][0] {    logo {      logo {        asset-> {          url        }      }    },  }
export type LogoQueryResult = {
  logo: {
    logo: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: ../web/sanity/queries/workshopDetails.ts
// Variable: workshopDetailsQuery
// Query: *[_type == "workshop" && slug.current == $slug][0] {    _id,    title,    slug,    description,    datetime,    location,    duration,    group,    status,    image {      asset-> {        _id,        _ref,        url,        metadata {          lqip,          dimensions        },        altText,        title,        description      },      crop,      hotspot    },    signupFormUrl,    materials {      asset-> {        _ref,        url,        originalFilename      }    },  }
export type WorkshopDetailsQueryResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  datetime: string | null;
  location: string | null;
  duration: number | null;
  group: "adult" | "children" | "family" | "teen" | null;
  status: "completed" | "inProgress" | "planned" | null;
  image: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
      altText: string | null;
      title: string | null;
      description: string | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  signupFormUrl: string | null;
  materials: {
    asset: {
      _ref: null;
      url: string | null;
      originalFilename: string | null;
    } | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "workshop"] | order(_createdAt desc)': WorkshopsQueryResult;
    '\n  *[_type == "home"][0]{\n    _id,\n    sections[]{\n      ...,\n      _type in ["cardswithbackground", "sectionCardsWithBackground"] => {\n        ...,\n        cards[]->{\n          _id,\n          title,\n          description,\n          image\n        }\n      },\n      _type in ["cardswithredirect", "sectionCardsWithRedirect"] => {\n        ...,\n        cards[]->{\n          _id,\n          title,\n          description,\n          href,\n          hrefText,\n          image\n        },\n        button->{\n          _id,\n          text,\n          href\n        }\n      },\n      _type in ["supportSection", "sectionSupport"] => {\n        ...,\n        button->{\n          _id,\n          text,\n          href\n        }\n      },\n      _type in ["cooperationSection", "sectionCooperation"] => {\n        ...,\n        button->{\n          _id,\n          text,\n          href\n        }\n      }\n    }\n  }\n': HomeQueryResult;
    '\n  *[_type == "post"] | order(_createdAt desc) {\n    _id,\n    _createdAt,\n    title,\n    "slug": slug.current,\n    "author": author->name,\n    "image": mainImage.asset->url,\n    description,\n    "categories": categories[]->title,\n    body\n  }\n': PostsQueryResult;
    '\n  *[_type == "material"] | order(date desc) {\n    _id,\n    title,\n    description,\n    date,\n    event,\n    type,\n    area,\n    format,\n    size,\n    placements,\n    "fileAsset": file.asset->{\n      url,\n      extension,\n      size\n    }\n  }\n': MaterialsQueryResult;
    '\n  *[_type == "settings"][0] {\n    logo {\n      logo {\n        asset-> {\n          url\n        }\n      }\n    },\n    link {\n      socialLinks {\n        facebook,\n        instagram,\n        linkedin\n      }\n    }\n  }\n': SettingsQueryResult;
    '\n  *[_type == "settings"][0] {\n    logo {\n      logo {\n        asset-> {\n          url\n        }\n      }\n    },\n  }\n': LogoQueryResult;
    '\n  *[_type == "workshop" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    description,\n    datetime,\n    location,\n    duration,\n    group,\n    status,\n    image {\n      asset-> {\n        _id,\n        _ref,\n        url,\n        metadata {\n          lqip,\n          dimensions\n        },\n        altText,\n        title,\n        description\n      },\n      crop,\n      hotspot\n    },\n    signupFormUrl,\n    materials {\n      asset-> {\n        _ref,\n        url,\n        originalFilename\n      }\n    },\n  }\n': WorkshopDetailsQueryResult;
  }
}
